main = "workers-site/index.js"

name = "11ty_barbershop"
account_id = "889c69c3a2ed27db8cbfdc65709ba4dd"
workers_dev = false
route = "stylebarbershop.info/*"

compatibility_date = "2023-10-04"

[site]
bucket = "./_site"